project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: auto
  engine: knitr
  port: 8877
  cache: true

website:
  title: "Emily:"
  back-to-top-navigation: true
  page-navigation: true

  navbar:
    left:
      - href: index.qmd
        text: Goal
      - href: LOGO_Emily.qmd
        text: Logo 

format:
  html:
    theme: cosmo
    toc: true
    code-link: true
    code-copy: true
    code-tools: true
    code-fold: false
    code-overflow: wrap
    page-layout: full
    css: styles.css

editor: visual
